g4-dev/src-ecs

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/php.yml
- docs/1Installation.md
- docs/2Stack.md
- docs/4Tests.md
- docs/6KnowedErrors.md
- www/composer.json
- www/composer.lock
- www/config/packages/easy_admin.yaml
- www/config/packages/framework.yaml
- www/config/packages/mailer.yaml
- www/config/packages/security.yaml
- www/config/packages/validator.yaml
- www/config/services.yaml
- www/fixtures/data/dev/random_admins.yml
- www/fixtures/data/dev/random_users.yml
[34jeq3](https://app.clickup.com/t/34jeq3)
- Nettoyage des configs
[x] Le titre de ma PR contient bien l'id de mon ticket<br>
[x] Mon historique est correcte <br>
[x] Je merge sur la branche demandée par mon ticket <br>
[x] J'ai mis à jour ma branche avec la remote `g4-dev`<br>
[x] J'ai bien enlevé les commandes de debuggage
> [34jeq3] - Better Docs & configs

- www/assets/front_office/scss/categories.scss
[https://app.clickup.com/t/2whcz0](#2whcz0) 
- j'ai mis couleur chartreuse
- [ x ] Le titre de ma PR contient bien l'id de mon ticket<br>
[ ] Mon historique est correcte <br>
[ ] Je merge sur la branche demandée par mon ticket <br>
[ ] J'ai mis à jour ma branche avec la remote `g4-dev`<br>
[ ] J'ai bien enlevé les commandes de debuggage
> [ci skip][#2whcz0] - bite

- .idea/dataSources.local.xml
- .idea/dataSources.xml
- .idea/deployment.xml
- vm_config.yaml
- www/config/packages/doctrine.yaml
- www/src/FrontOffice/Entity/Admin.php
- www/src/FrontOffice/Entity/Comment.php
- www/src/FrontOffice/Entity/PaymentData.php
- www/src/FrontOffice/Entity/PaymentDetails.php
- www/src/FrontOffice/Entity/PaymentType.php
- www/src/FrontOffice/Entity/Product.php
- www/src/FrontOffice/Entity/ProductType.php
- www/src/FrontOffice/Entity/Shipment.php
- www/src/FrontOffice/Entity/ShipmentDetails.php
- www/src/FrontOffice/Entity/ShipmentStatus.php
- www/src/FrontOffice/Entity/ShipmentType.php
- www/src/FrontOffice/Entity/StatusCatalog.php
- www/src/FrontOffice/Entity/Stock.php
- www/src/FrontOffice/Entity/User.php
[ ] Le titre de ma PR contient bien l'id de mon ticket<br>
[ ] Mon historique est correcte <br>
[ ] Je merge sur la branche demandée par mon ticket <br>
[ ] J'ai mis à jour ma branche avec la remote `g4-dev`<br>
[ ] J'ai bien enlevé les commandes de debuggage
> Reverse Ingeniring all entities are created

- www/config/packages/security.yaml
- www/fixtures/data/dev/random_users.yml
- www/fixtures/data/dev/test_user.yml
- www/src/Core/Entity/User.php
- www/src/FrontOffice/Controller/RegistrationController.php
- www/src/FrontOffice/Form/AccountUpdateForm.php
- www/src/FrontOffice/Form/RegistrationForm.php
- www/templates/front_office/accounting/account-update.html.twig
- www/templates/front_office/accounting/show-account.html.twig
- www/templates/front_office/forms/account-update-form.html.twig
- www/templates/front_office/homepage.html.twig
- www/templates/front_office/partials/header.html.twig
> [#3ahbpt] - Modifications des informations du compte

- www/assets/front_office/homepage.ts
- www/assets/front_office/recetteDIY.ts
- www/assets/front_office/scss/app.scss
- www/assets/front_office/scss/partials/_mixins.scss
- www/assets/front_office/scss/partials/layout.scss
- www/assets/front_office/scss/partials/reset.scss
- www/assets/front_office/scss/recetteDIY.scss
- www/templates/front_office/diy/show.html.twig
- www/templates/front_office/partials/header.html.twig
Finalisation du système statique, besoin d'un ajustement responsif au niveau des caractéristiques
Mise en place de la page pour une seule recette avec gestion de la difficulté.
> Product DIY (#23)

- Makefile
- Vagrantfile
> Env: rsync mode to upload files

- www/assets/front_office/scss/app.scss
- www/assets/front_office/scss/company.scss
- www/assets/front_office/scss/diy_list.scss
> Fix responsive page company

- www/assets/front_office/homepage.ts
- www/assets/front_office/professional.ts
- www/assets/front_office/scss/app.scss
- www/assets/front_office/scss/partials/layout.scss
- www/assets/front_office/scss/professional.scss
- www/config/packages/security.yaml
- www/config/pages.yml
- www/src/FrontOffice/Controller/Professional.php
- www/templates/front_office/professional.html.twig
https://app.clickup.com/t/2whcv2
Yes
professional.html.twig
http://ecoservice.cum/pro
> Page espace pro #2whcv2

- www/translations/messages.fr.yml
> Traduction

- www/assets/front_office/compAndDechet.ts
- www/assets/front_office/company.ts
- www/assets/front_office/scss/app.scss
- www/assets/front_office/scss/compAndDechet.scss
- www/assets/front_office/scss/partials/layout.scss
- www/config/pages.yml
- www/src/FrontOffice/Controller/ZeroDechetController.php
- www/templates/front_office/zerodechet.html.twig
https://app.clickup.com/t/2whe2n
Exactement le même entrypoints que company
http://ecoservice.cum/zerodechet
> Ajout de la page Zero Dechet #2whe2n

- www/assets/front_office/homepage.ts
- www/assets/front_office/scss/app.scss
- www/assets/front_office/scss/homepage.scss
- www/templates/front_office/homepage.html.twig
homepage : bouton du slider à cliquer
> Fix du bug quand la page height -100vh, slider homepage

- www/src/Admin/Entity/Nav.php
- www/templates/front_office/accounting/password-reminder.html.twig
- www/templates/front_office/accounting/password-reset.html.twig
> fix fix fix flash

- www/src/FrontOffice/Controller/ProController.php
- www/src/FrontOffice/Form/Accounting/DevisForm.php
- www/templates/front_office/proDevis.html.twig
- www/templates/front_office/proServiceList.html.twig
Numéro du ticket: 3mfut6
Route= /services-pro/devis
> Form demande de devis

- www/assets/easyadmin/scss/easyadmin-theme/base.scss
- www/assets/easyadmin/scss/easyadmin-theme/buttons.scss
- www/assets/easyadmin/scss/easyadmin-theme/datagrids.scss
- www/assets/easyadmin/scss/easyadmin-theme/forms.scss
- www/assets/easyadmin/scss/easyadmin-theme/menu.scss
- www/assets/easyadmin/scss/easyadmin-theme/select2.scss
- www/assets/easyadmin/scss/easyadmin-theme/switches.scss
- www/assets/easyadmin/scss/easyadmin-theme/variables.css
- www/assets/easyadmin/scss/easyadmin-theme/variables.scss
- [x ] J'ai mis à jour ma branche avec la remote `g4-dev`<br>
> Design Backoffice (Easy admin css)

- www/assets/front_office/scss/app.scss
- www/assets/front_office/scss/diyList.scss
- www/assets/front_office/scss/homepage.scss
- www/assets/front_office/scss/partials/layout.scss
- www/assets/front_office/ts/partials/layout.ts
- www/assets/front_office/ts/partials/popup.ts
- www/templates/front_office/cms/diyList.html.twig
- www/templates/front_office/homepage.html.twig
- www/templates/front_office/partials/header.html.twig
[42fqfx](https://app.clickup.com/t/42fqfx)
> 42fqfx - MAJ Home + popup

- www/assets/front_office/scss/accounting.scss
- www/src/Admin/Command/InitSettingsCommand.php
- www/templates/front_office/accounting/show-account.html.twig
> Fix Fixtures

- www/assets/front_office/scss/accounting.scss
- www/assets/front_office/scss/partials/show-account.scss
- www/templates/front_office/accounting/show-account.html.twig
> Front page Mon compte

- www/assets/easyadmin/scss/easyadmin-theme/base.scss
- www/assets/easyadmin/scss/easyadmin-theme/buttons.scss
- www/assets/easyadmin/scss/easyadmin-theme/datagrids.scss
- www/assets/easyadmin/scss/easyadmin-theme/forms.scss
- www/assets/easyadmin/scss/easyadmin-theme/menu.scss
- www/assets/easyadmin/scss/easyadmin-theme/variables.css
- www/src/Admin/Controller/AdminController.php
- www/src/Admin/Repository/CategoryRepository.php
- www/src/Admin/Repository/DiyRepository.php
- www/src/Admin/Repository/ProductRepository.php
- www/src/FrontOffice/Entity/Purchase.php
- www/src/FrontOffice/Repository/PurchaseRepository.php
- www/templates/bundles/EasyAdminBundle/default/layout.html.twig
- www/templates/bundles/EasyAdminBundle/default/paginator.html.twig
> Front du backoffice

- www/assets/front_office/scss/productList.scss
- www/assets/front_office/scss/productShow.scss
- www/assets/front_office/ts/components/product.js
- www/assets/front_office/ts/components/product.ts
- www/config/services.yaml
- www/src/FrontOffice/Controller/ProductController.php
- www/templates/front_office/partials/header.html.twig
- www/templates/front_office/shopping/productAll.html.twig
- www/templates/front_office/shopping/productShow.html.twig
> Produits dynamiques

- www/assets/front_office/accounting.ts
- www/assets/front_office/scss/accounting.scss
- www/assets/front_office/scss/homepage.scss
- www/assets/front_office/scss/proServiceList.scss
- www/src/FrontOffice/Controller/FooterController.php
- www/templates/front_office/accounting/account-update.html.twig
- www/templates/front_office/legalPage/contact.html.twig
- www/templates/front_office/legalPage/data.html.twig
- www/templates/front_office/legalPage/mentions.html.twig
- www/templates/front_office/partials/footer.html.twig
- www/templates/front_office/proDevis.html.twig
> page contact, mentions, rgpd

- www/config/packages/easy_admin/marketing/cms_page.yml
- www/config/packages/easy_admin/marketing/newsletter.yml
- www/src/Admin/Entity/CmsCategory.php
- www/src/Admin/Entity/NewsLetter.php
- www/src/Admin/Entity/TitleContent.php
- www/src/Core/Service/PurchaseFactoryService.php
- www/src/FrontOffice/Controller/Accounting/RegistrationController.php
- www/src/FrontOffice/Controller/ProductController.php
- www/src/FrontOffice/Controller/Shopping/BasketController.php
- www/src/FrontOffice/Form/Shopping/AddToBasketType.php
- www/templates/front_office/shopping/basket.html.twig
- www/templates/front_office/shopping/productShow.html.twig
> Home basket pay

- www/assets/easyadmin/scss/easyadmin-theme/base.scss
- www/assets/easyadmin/scss/easyadmin-theme/buttons.scss
- www/assets/easyadmin/scss/easyadmin-theme/datagrids.scss
- www/assets/easyadmin/scss/easyadmin-theme/forms.scss
- www/config/services.yaml
- www/src/Admin/Controller/AdminController.php
- www/templates/bundles/EasyAdminBundle/dashboard.html.twig
- www/templates/bundles/EasyAdminBundle/default/paginator.html.twig
> Tableau bord back

- www/assets/front_office/scss/productList.scss
- www/assets/front_office/scss/productShow.scss
- www/assets/front_office/ts/components/product.js
- www/config/packages/easy_admin/ecommerce/abstract_category.yml
- www/config/packages/easy_admin/ecommerce/product_category.yml
- www/templates/front_office/shopping/productList.html.twig
- www/templates/front_office/shopping/productShow.html.twig
- www/translations/easyadmin/messages.fr.yml
* Amélioration dynamisme produit
* Affichage produit
> Produits dynamiques (#77)

- www/assets/front_office/ts/components/product.js
- www/fixtures/DataFixtures/Prod/LoadProducts.php
- www/templates/bundles/EasyAdminBundle/page/login.html.twig
- www/templates/front_office/accounting/account-update.html.twig
- www/templates/front_office/accounting/admin-login.html.twig
- www/templates/front_office/accounting/login.html.twig
- www/templates/front_office/accounting/show-account.html.twig
- www/templates/front_office/cms/diyShow.html.twig
- www/templates/front_office/legalPage/contact.html.twig
- www/templates/front_office/proServiceList.html.twig
- www/templates/front_office/shopping/productList.html.twig
- www/templates/front_office/shopping/productShow.html.twig
> Fix js product + nom de page

- www/assets/front_office/scss/homepage.scss
- www/templates/front_office/homepage.html.twig
> fix home pro_parti

- www/assets/front_office/scss/purchasing.scss
- www/templates/front_office/shopping/purchaseList.html.twig
> Commandes push

- www/assets/front_office/scss/accounting.scss
- www/assets/front_office/scss/app.scss
- www/assets/front_office/scss/diyList.scss
- www/templates/front_office/components/pagination.html.twig
> pagination

- www/assets/front_office/scss/app.scss
- www/assets/front_office/ts/partials/layout.ts
- www/templates/front_office/components/flash-messages.html.twig
Qu’il est loin ce mois de décembre 2019, où j’ai mi les pieds pour la première fois dans notre entreprise. Et qu’il semble si proche pourtant…
Les années filent et voilà que s’ouvre une nouvelle porte…
De nouvelles opportunités, un nouveau chemin, une nouvelle vie aussi…
Une nouvelle page à tourner dans le livre de mon histoire professionnelle et personnelle.
Avant mon départ, mes chers collègues, je voudrais vous exprimer ma grande reconnaissance et ma profonde estime. Avoir travailler à vos côtés, avoir partagé mon quotidien professionnel avec vous fut une grande et riche expérience professionnelle et personnelle pour moi.
Merci à tous mes collègues que je quitte aujourd’hui.
GRAND MERCI à vous pour votre accueil, gentillesse et bienveillance.
A chacune et chacun, je souhaite une bonne …
> flash message style

- www/fixtures/DataFixtures/Prod/LoadCategories.php
- www/fixtures/DataFixtures/Prod/LoadProducts.php
- www/templates/front_office/partials/footer.html.twig
> Bordel antoine

- www/package.json
- www/yarn.lock
> update babel - fix minimist (pending)
